---
title: "Week 3 Exercise"
author: "Vikas"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
i <- sample(2, nrow(cars), replace = TRUE, prob = c(0.8,0.2))
carsTrainingData<-cars[i==1,]
carsTestingData<-cars[i==2,]
summary(cars)
summary(carsTestingData)
summary(carsTrainingData)
```

```{r iris}
i <- sample(2, nrow(iris), replace = TRUE, prob = c(0.6,0.4))
irisTrainingData<-iris[i==1,]
irisTestingData<-iris[i==2,]
summary(iris)
summary(irisTestingData)
summary(irisTrainingData)

par(mfrow = c(1,3))
hist(iris$Sepal.Width, seq(min(iris$Sepal.Width),max(iris$Sepal.Width), l=10), col="red")
hist(irisTestingData$Sepal.Width, seq(min(irisTestingData$Sepal.Width),max(irisTestingData$Sepal.Width), l=10), col="green")
hist(irisTrainingData$Sepal.Width, seq(min(irisTrainingData$Sepal.Width),max(irisTrainingData$Sepal.Width), l=10), col="blue")

par(mfrow = c(1,3))
boxplot(iris$Sepal.Length)
boxplot(irisTestingData$Sepal.Length)
boxplot(irisTrainingData$Sepal.Length)

par(mfrow = c(1,3))
barplot(table(iris$Species))
barplot(table(irisTestingData$Species))
barplot(table(irisTrainingData$Species))
```

#Day 2

```{r }
n<- 10000
x <- c(0,1)
sumsInReoeatedSampling10Reps<-replicate(10, sum(sample(x, size=n, replace=TRUE)))
sumsInReoeatedSampling100Reps<-replicate(100, sum(sample(x, size=n, replace=TRUE)))
sumsInReoeatedSampling1000Reps<-replicate(1000, sum(sample(x, size=n, replace=TRUE)))

par(mfrow = c(1,3))
hist(sumsInReoeatedSampling10Reps, col="green", main =paste("Number of heads- 10 reps"))
hist(sumsInReoeatedSampling100Reps, main =paste("Number of heads- 100 reps"))
hist(sumsInReoeatedSampling1000Reps, col="red", main =paste("Number of heads- 1000 reps"))

```

```{r }
meansOfX<-c(mean(sumsInReoeatedSampling10Reps), mean(sumsInReoeatedSampling100Reps), mean(sumsInReoeatedSampling1000Reps))
varsOfX<-c(var(sumsInReoeatedSampling10Reps), var(sumsInReoeatedSampling100Reps), var(sumsInReoeatedSampling1000Reps))
meansOfX
varsOfX